---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-credentials
  namespace: flux-system
type: Opaque
stringData:
  #identity: $(cat ${HOME}/.ssh/demo_key_rsa|base64|tr -d '\n')
  #known_hosts: $(ssh-keyscan -t rsa github.com 2>/dev/null|grep -E '^github\.com'|base64|tr -d '\n')
  username: QWJkZWxhbGkxMi1jb2Rlcwo=
  password: Z2hwX1J6Rzh0Q2pDVFk0dHgzaFR1Z2plcVBoRlNPM2EyZzFvaDdLRgo=
  
  #https://fluxcd.io/flux/components/source/gitrepositories/#url