---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k8s-flux
  namespace: flux-system
spec:
  interval: 2m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux
  path: "./manifest"
  prune: true
  